[keyboard]
	bindings = [
    	{ key = "C", mods = "Control|Shift", action = "Copy" },
    	{ key = "V", mods = "Control|Shift", action = "Paste" },
	]

[mouse]
	bindings = [
		{ mouse = "Right", action = "Copy" },
	]

[font]
size = 14.0

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[terminal]

[terminal.shell]
args = ["--login"]
program = "/usr/bin/zsh"
